{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "5.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "bveza4zlrreyxjgjup623k2yw4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-5.3.4.jar",
          "url": "spring-expression-5.3.4.jar",
          "size": 282596,
          "sha512": "e11fb9fc6ab64c0b66e55aaf0ae2bacbe23584b1a3e33591fe2b59f7259eeee28b028d81366188901b408ca79586c9e455a642df1493317d45ad752a18e2e124",
          "sha256": "27707558975fdf0555682c24af22b9970dab38b4f8ea79b074200c79dc60460f",
          "sha1": "42b71fa955e43a86471509aef14cefe756fc3794",
          "md5": "1561287147d929c1851c6b3a66f41598"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-5.3.4.jar",
          "url": "spring-expression-5.3.4.jar",
          "size": 282596,
          "sha512": "e11fb9fc6ab64c0b66e55aaf0ae2bacbe23584b1a3e33591fe2b59f7259eeee28b028d81366188901b408ca79586c9e455a642df1493317d45ad752a18e2e124",
          "sha256": "27707558975fdf0555682c24af22b9970dab38b4f8ea79b074200c79dc60460f",
          "sha1": "42b71fa955e43a86471509aef14cefe756fc3794",
          "md5": "1561287147d929c1851c6b3a66f41598"
        }
      ]
    }
  ]
}
